### ISSUE TITLE
Test environment?

### ISSUE THREAD

**Issue by shaung** [PhonePe/phonepe-php#2]
I am trying to integrate with the phonepe UPI payment.

From what I found in https://developer.phonepe.com, I need a merchant id and a secret key to get started, and there is a test environment available. However I didn't find much information about how can I make use of the test environment.

The example in the `https://developer.phonepe.com/#regular-debit` section gives:
```
{
  "success": false,
  "code": "BAD_REQUEST",
  "message": "Please check the inputs you have provided.",
  "data": {}
}
```

**Comment by sanganagouda1** [comment]
i am also trying to implement ..but

**Comment by Anushapadinharepurakkal** [comment]
Hi, I have the same issue..is there any solution for this..i am doing this in Python

**Comment by Sreejit-Sengupto** [comment]
I think you need to send the data in base 64 encoding
